### ISSUE TITLE
Does not seem to work with ControlNet

### ISSUE THREAD

**Issue by setothegreat** [klimaleksus/stable-diffusion-webui-anti-burn#3]
ControlNet will be loaded, as can be seen by both VRAM usage and the speed of image generation compared to when it is disabled, but ControlNet doesn't seem to have any effect on the image so long as Anti Burn is enabled.

**Comment by aleksusklim** [comment]
Interesting, will look into that, thank you.

**Comment by aleksusklim** [comment]
Which control model do you use?

I tried openpose+control_v11p_sd15_openpose on commit `22bcc7be428c94e9408f589966c2040187245d81` and everything seems to work fine as intended.

If you tell me more details, I will look and test further.

**Comment by setothegreat** [comment]
> Which control model do you use?
> 
> I tried openpose+control_v11p_sd15_openpose on commit `22bcc7be428c94e9408f589966c2040187245d81` and everything seems to work fine as intended.
> 
> If you tell me more details, I will look and test further.

Can't remember exactly what I was using at the time of this report since I have upgraded to the new 1.1 models in the past month, but I'm pretty sure it was the non-T2I depth model for 1.5, likely combined with either a sketch, normal, or canny model.
